# Generated by Django 2.2.4 on 2019-08-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('quote', models.CharField(max_length=1024)),
                ('personal_item', models.CharField(max_length=256)),
                ('carry_on', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
