# Generated by Django 2.2.4 on 2019-08-15 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercedes', '0002_auto_20190815_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercedes',
            name='carry_on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='carry_on', to='passengers.CarryOn'),
        ),
    ]
