# Generated by Django 2.2.4 on 2019-08-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercedes', '0003_auto_20190815_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercedes',
            name='money',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
