# Generated by Django 2.2.4 on 2019-08-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_carryon'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryon',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='passengers.Passenger'),
        ),
    ]
