# Generated by Django 2.2.4 on 2019-08-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_auto_20190815_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carryon',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passenger',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='passengers.CarryOn'),
        ),
    ]
