# Generated by Django 2.2.4 on 2019-08-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_auto_20190815_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='item',
        ),
        migrations.AddField(
            model_name='passenger',
            name='carry_on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='carry_on', to='passengers.CarryOn'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='personal_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='personal_item', to='passengers.CarryOn'),
        ),
    ]
