# Generated by Django 2.2.4 on 2019-08-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0006_auto_20190815_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
