# Generated by Django 2.2.4 on 2019-08-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0007_delete_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carryon',
            name='attack',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
