# Generated by Django 2.2.4 on 2019-08-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0007_delete_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaireMiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Claire Miller', max_length=256)),
                ('job', models.CharField(default='Flight Attendant', max_length=20)),
                ('imageUrl', models.CharField(default='/ClaireMiller/src/clare_profile.jpg', max_length=255)),
                ('flavorText', models.CharField(default='Claire Miller is a determined, resourceful woman with the strength to survive any catastrophe', max_length=255)),
                ('carry_on', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='carry_on', to='passengers.CarryOn')),
                ('personal_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='personal_item', to='passengers.CarryOn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
